version: '3'
services:
  admin_backend:
    build: .
    image: antoniopapa/admin:0.0.2
    command: "npm run start:dev"
    ports:
      - 8002:3000
    environment:
      BOOSTRAP_SERVERS: pkc-4ygn6.europe-west3.gcp.confluent.cloud:9092
      SASL_USERNAME: 6567MKPS6YFGEMJH
      SASL_PASSWORD: zaf8YnUY/BzmTpNk6TFC+wJQQ0YoQdvmwfRQTRtRo19YZChYEev2Wkx+rG3Two2h
      GROUP_ID: admin-consumer
      DB_HOST: 35.234.72.130
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
      USERS_MS: http://users-backend:8001

  admin_consumer:
    build: .
    image: antoniopapa/admin:0.0.2
    command: "npm run consume"
    environment:
      BOOSTRAP_SERVERS: pkc-4ygn6.europe-west3.gcp.confluent.cloud:9092
      SASL_USERNAME: 6567MKPS6YFGEMJH
      SASL_PASSWORD: zaf8YnUY/BzmTpNk6TFC+wJQQ0YoQdvmwfRQTRtRo19YZChYEev2Wkx+rG3Two2h
      GROUP_ID: admin-consumer
      DB_HOST: 35.234.72.130
      DB_PORT: 3306
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: root
      USERS_MS: http://users-backend:8001

