apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-backend
  name: admin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-backend
  template:
    metadata:
      labels:
        io.kompose.service: admin-backend
    spec:
      containers:
        - args:
            - npm
            - run
            - start:dev
          env:
            - name: BOOSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOSTRAP_SERVERS
            - name: DB_DATABASE
              value: admin
            - name: DB_HOST
              value: 35.234.72.130
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: admin-consumer
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: USERS_MS
              value: http://users-ms:3000
          image: antoniopapa/admin:0.0.1
          name: admin-backend
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: admin-consumer
  name: admin-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-consumer
  template:
    metadata:
      labels:
        io.kompose.service: admin-consumer
    spec:
      containers:
        - args:
            - npm
            - run
            - consume
          env:
            - name: BOOSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOSTRAP_SERVERS
            - name: DB_DATABASE
              value: admin
            - name: DB_HOST
              value: 35.234.72.130
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: admin-consumer
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: USERS_MS
              value: http://users-ms:3000
          image: antoniopapa/admin:0.0.1
          name: admin-consumer
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: admin-backend
  name: admin-backend
spec:
  ports:
    - name: "8002"
      port: 8002
      targetPort: 3000
  selector:
    io.kompose.service: admin-backend
