apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ambassador-backend
  name: ambassador-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ambassador-backend
  template:
    metadata:
      labels:
        io.kompose.service: ambassador-backend
    spec:
      containers:
        - args:
            - npm
            - run
            - start:dev
          env:
            - name: BOOSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOSTRAP_SERVERS
            - name: DB_DATABASE
              value: ambassador
            - name: DB_HOST
              value: 35.246.225.225
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: ambassador-consumer
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: USERS_MS
              value: http://users-backend:8001
          image: antoniopapa/ambassador:0.0.1
          name: ambassador-backend
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ambassador-consumer
  name: ambassador-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ambassador-consumer
  template:
    metadata:
      labels:
        io.kompose.service: ambassador-consumer
    spec:
      containers:
        - args:
            - npm
            - run
            - consume
          env:
            - name: BOOSTRAP_SERVERS
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: BOOSTRAP_SERVERS
            - name: DB_DATABASE
              value: ambassador
            - name: DB_HOST
              value: 35.246.225.225
            - name: DB_PASSWORD
              value: root
            - name: DB_PORT
              value: "3306"
            - name: DB_USERNAME
              value: root
            - name: GROUP_ID
              value: ambassador-consumer
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_PASSWORD
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-secrets
                  key: SASL_USERNAME
            - name: USERS_MS
              value: http://users-backend:8001
          image: antoniopapa/ambassador:0.0.1
          name: ambassador-consumer
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: ambassador-backend
  name: ambassador-backend
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 3000
  selector:
    io.kompose.service: ambassador-backend
