version: '3.9'
services:
  users_backend:
    build: .
    container_name: users-ms
    ports:
      - 8001:3000
    environment:
      DB_HOST: users_db
      DB_PORT: 3306
      DB_DATABASE: users
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/app
    depends_on:
      - users_db
    networks:
      - users

  users_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    networks:
      - users

networks:
  users:
    name: users
